name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/test-clang-format
      with: 
        exclude: './.github'
        clang-format-version: 9