name: test-clang-format1

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.16.1
      with: 
        exclude: './.github'
        source: 'src src2'
        clangFormatVersion: 16
        inplace: False
