name: test-clang-format

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.8
      with: 
        exclude: './.github'
        source: 'src src2 src1'
        clangFormatVersion: 10      
